apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory
  template:
    metadata:
      labels:
        app: memory
    spec:
      containers:
      - name: memory
        image: progrium/stress
        args: ["--vm", "1", "--vm-bytes", "500M"]
        resources:
          limits:
            memory: "100Mi"
